Added UT cases for start_indexing and indexing
OpenMPDK/dss-ecosystem pull request #65
Opened 2023-08-09 14:16 UTC by Chenliang-Eric-Li

Added ut cases for master_application.start_indexing task.iterate_dir and task.indexing in test_datamover.py.
Mocked nfs_cluster class, os.Entry class and some os functions in conftest.py #64

2023-08-09 17:03 UTC, nsarras requested changes
great job, just need to make a few changes

2023-08-11 10:52 UTC, Chenliang-Eric-Li commented on dss_datamover/tests/conftest.py
> +    test_config_filepath = "/etc/dss/datamover/standard_config.json"
Removed this line and put all the configures in pytest_config.json.

2023-08-11 10:53 UTC, Chenliang-Eric-Li commented on dss_datamover/tests/conftest.py
> +    def __init__(self, family=0, type=0, proto=0, fileno=0):
restored MockSocket class to its original state.

2023-08-11 10:54 UTC, Chenliang-Eric-Li commented on dss_datamover/tests/conftest.py
> +class MockEntry():
it's called MockDirEntry now.

2023-08-11 10:54 UTC, Chenliang-Eric-Li commented on dss_datamover/tests/conftest.py
> +def mock_os_scan_dir(dir):
they are in a MockOSDirOperations class now.

2023-08-14 17:09 UTC, nsarras approved these changes

2023-08-22 19:56 UTC, nsarras commented
Please pull in latest changes from master and conform to the new test structure

2023-08-31 17:18 UTC, nsarras commented
@Chenliang-Eric-Li branch conflicts need to be resolved

2023-08-31 17:18 UTC, nsarras commented
@Chenliang-Eric-Li is this a copy of another PR? we need to focus on one at a time and make sure there are no overlapping changes

2023-09-01 08:55 UTC, closed without merging